# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-02 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(default='', max_length=100)),
                ('bookimage', models.ImageField(default='', upload_to='images')),
                ('bookauthor', models.CharField(default='', max_length=100)),
                ('bookpublisher', models.CharField(default='', max_length=100)),
                ('bookreview', models.CharField(default='', max_length=1000)),
                ('authorscomments', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
