# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-16 12:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookreview', '0003_uservote_dateposted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together=set([('user', 'book')]),
        ),
    ]
