# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-17 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookreview', '0004_auto_20191116_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservote',
            old_name='user',
            new_name='loggeduser',
        ),
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together=set([('loggeduser', 'book')]),
        ),
    ]
