# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-21 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0008_auto_20191215_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='monthwinner',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
