# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-21 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0010_remove_bookreview_monthwinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='monthwinner',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
