# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-22 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0012_auto_20200221_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='bookname',
            new_name='booknamereview',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='booknamevote',
            field=models.CharField(default='', max_length=100),
        ),
    ]
