# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-22 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0013_auto_20200222_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='booknamevote',
        ),
    ]
