# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-22 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0015_auto_20200222_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booknamechoice', models.CharField(default='', max_length=100)),
                ('bookchoiceimage', models.ImageField(default='', upload_to='images')),
                ('bookchoiceauthor', models.CharField(default='', max_length=100)),
                ('bookchoicepublisher', models.CharField(default='', max_length=100)),
                ('authorschoicecomments', models.CharField(default='', max_length=1000)),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='uservote',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookreview.BookChoice'),
        ),
    ]
