# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-21 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20191026_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_decription',
            field=models.CharField(default='description', max_length=10000),
        ),
    ]
