# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-11 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200111_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address',
            new_name='delivery_street_address',
        ),
    ]
