# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-25 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190923_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='m2_coverage',
            field=models.DecimalField(decimal_places=2, default='10.64', max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AddField(
            model_name='product',
            name='recomended_for',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='thermal_value',
            field=models.DecimalField(decimal_places=2, default='0.22', max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='thickness',
            field=models.DecimalField(decimal_places=1, default='12.5', max_digits=4),
        ),
    ]
